

> **ShortCut for dataScience Tool like google collab.**

1.   *shift + Enter = codeRun and open next cell .*
2.   *control + Enter = CodeRun.*



In [ ]:
import numpy as np

# create array

In [ ]:
array = np.array([1,2,3,4,5,6])
print(array)
array_2d = np.array( [ [1,2,3,4,5],[5,4,3,2,1],[1,2,3,4,5],[5,4,3,2,1] ] )
print(array_2d) 

# Array details

In [ ]:
a = array_2d.size   # total presented element 
b = array_2d.ndim   # array dimention 
c = array_2d.shape  # (row, colomn) ==> (4,5)
d = array_2d.dtype  # array type

print([a,b,c,d])

# Zero And One Numpy Array 


In [ ]:
# np.ones((row,colomn), dtype)

array_zero = np.zeros((4,6))
array_ones = np.ones((5,2),dtype=int) 

print(array_ones)

In [ ]:
empty_array = np.empty((4,5))
empty_array

#  Some important function in numpy 






*arrange()*

In [ ]:
#  np.arange(strat, End, Step )
a_arrange = np.arange(1,13,2)
print(a_arrange)

linspace()

In [ ]:
# np.linspace(strat, ending , ElementNumber)
a_linehape = np.linspace(1,5,10)
print(a_linehape)

reshape()

In [ ]:
# array.reshape()
a_value = np.arange(1,13).reshape(3,4) #2d
print(a_value)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
ayush = np.arange(1,17).reshape(4,2,2) #3d
ayush

ravel()

In [ ]:
ayush.ravel() # convert 1D array

transpose()

In [ ]:
a_value.transpose() # row covert into colomn && colomn convert into row

#  Math Calculation Numpy

In [ ]:
 arr1 = np.arange(1,13).reshape(3,4)
 arr2 =  np.arange(12,24).reshape(3,4)
 
 arr1
 arr2


In [ ]:
arr1 + arr2

In [ ]:
arr1 - arr2

In [ ]:
arr1 * arr2

In [ ]:
arr1 / arr2

In [ ]:
 arr1 = np.arange(1,13).reshape(3,4)
 arr2 =  np.arange(12,24).reshape(4,3)
 arr1@arr2 # cartician 

# Find Min & Max value

In [ ]:
arr1 = np.array([[ 10,26,30,4],[ 5,90,70,4],[ 9,5,6,80]])
print(arr1)

[[10 26 30  4]
 [ 5 90 70  4]
 [ 9  5  6 80]]


In [ ]:
arr1.max() # max Number in full array
arr1.min() # min Number in full array

In [ ]:
arr1.argmax() # position of min Number in full matrix 
arr1.argmin() # position of max Number in full matrix 

In [ ]:
arr1.max(axis=0) # max number of every coloumn in matrix

In [ ]:
arr1.max(axis=1) # max number of every row in matrix

In [ ]:
arr1.sum() # sum all matrix

In [ ]:
arr1.sum(axis=0) # sum column matrix

In [ ]:
arr1.sum(axis=1) # sum row matrix

In [ ]:
arr1.mean() # avarage in full matrix

In [ ]:
arr1.std() 

In [ ]:
np.exp(arr1) # exponent for every element

# Concatinate & Split

In [ ]:
array1 = np.arange(1,17).reshape(4,4)
array2 = np.arange(17,33).reshape(4,4)
np.concatenate((array1,array2))

In [ ]:
 np.concatenate((array1,array2),axis=1) # row

In [ ]:
 np.concatenate((array1,array2),axis=0) # column

In [ ]:
np.split(array1,2) # list ar modha duto array acha 

In [ ]:
np.split(array1,2, axis=1)

In [ ]:
np.split(array1,2, axis=0)

# Random matrix

In [ ]:
import random

In [ ]:
np.random.random((2,3))

In [ ]:
np.random.randint(1,29,(2,3)) # (range, shape)